export const productData = [
  {
    favorite: 'true',
    name: 'Publieke mandatendatabank',
    description:
      'Raadpleeg en hergebruik de gegevens van lokale mandatarissen in deze publiek toegankelijke mandatendatabank',
    'Startdatum dienstverlening': '',
    'Einddatum dienstverlening': 'nvt',
    categorie: 'Burger en Overheid',
    'Thema(’s)': 'Andere organisatie, Burger, Lokaal bestuur',
    'Meer thema’s': 'geen match',
    'Laatst gewijzigd': '2023-04-17',
    'Aangemaakt op': '2022-05-05',
    Procedure:
      "Procedure (U kunt zoeken op naam van de gemeente, provincie, OCMW of een Antwerps district.In de databank kunt u de volgende gegevens van de mandatarissen raadplegen:naam van de mandatarisde kieslijst waartoe hij of zij behoorthet mandaat in kwestiede eventuele (geplande) termijn van het mandaat.de bevoegdheden van de burgemeester, schepenen of gedeputeerdenOp het tweede blad 'Administratieve gegevens' vindt u de contactgegevens van het bestuur. Voor gemeenten vindt u er ook nog:de namen van de (adjunct-)secretaris, de financieel beheerder en de informatieambtenaarde politiezone.De lokale besturen zijn decretaal verplicht om via de Mandatendatabank de Vlaamse Regering binnen de 20 dagen op de hoogte te brengen van eedafleggingen van mandatarissen. Die informatieplicht geldt ook voor wijzigingen in de samenstelling van het bestuur.De lokale besturen kunnen zelf hun gegevens aanpassen via een beveiligde toegang tot de databank.De link naar de Mandatendatabank en meer informatie over het beheer vindt u op de website Lokaalbestuur.vlaanderen.be.)",
    Bewijsstukken: '',
    Kosten: '',
    'Financieel voordeel': '',
    Uitzonderingen: '',
    'Bevoegde bestuursniveau’s': 'Vlaamse overheid',
    'Bevoegde organisaties':
      'https://wegwijs.vlaanderen.be/#/organisations/OVO001835',
    'Uitvoerende bestuursniveau’s': 'Vlaamse overheid',
    'Uitvoerende organisaties': '',
    link: 'https://mandaten.lokaalbestuur.vlaanderen.be/',
    Regelgeving: '',
    'Links naar Vlaamse codex': '',
    Productnummer: '2229',
    Tags: '',
    Zoektermen: '',
    Publicatiekanalen: '',
    'Your Europe categorieën': '',
    Publicatielink:
      'Lees meer op vlaanderen.be, https://www.vlaanderen.be/Product/d23043c6-6e09-4797-bf41-3ec427d923eb',
    'Verwante producten': '',
    Deminimis: 'ongekend',
    'Gestructureerde voorwaarden': '',
    Subsidiemaatregel: '',
    'u/je versie': '31.8.0',
    Gearchiveerd: 'false',
    Conceptnummer: '',
    'Geografische toepassingsgebieden': 'Vlaams Gewest (BE2)',
    'Laatst ontvangen': '2024-01-30',
    Contactgegevens: '',
    filter: 'tools',
    filterTheme: 'burger',
  },
  {
    name: 'Lokale Producten-en Dienstencatalogus',
    description: 'Beheer uw lokale producten en diensten',
    'Startdatum dienstverlening': '',
    'Einddatum dienstverlening': 'nvt',
    categorie: 'Burger en Overheid',
    'Thema(’s)': 'Lokaal bestuur',
    'Meer thema’s': 'geen match',
    'Laatst gewijzigd': '',
    'Aangemaakt op': '',
    Procedure: '',
    Bewijsstukken: '',
    Kosten: '',
    'Financieel voordeel': '',
    Uitzonderingen: '',
    'Bevoegde bestuursniveau’s': 'Vlaamse overheid',
    'Bevoegde organisaties':
      'https://wegwijs.vlaanderen.be/#/organisations/OVO001835',
    'Uitvoerende bestuursniveau’s': 'Vlaamse overheid',
    'Uitvoerende organisaties': '',
    link: 'https://lpdc.lokaalbestuur.vlaanderen.be',
    Regelgeving: '',
    'Links naar Vlaamse codex': '',
    Productnummer: '',
    Tags: '',
    Zoektermen: '',
    Publicatiekanalen: '',
    'Your Europe categorieën': '',
    Publicatielink: '',
    'Verwante producten': '',
    Deminimis: '',
    'Gestructureerde voorwaarden': '',
    Subsidiemaatregel: '',
    'u/je versie': '',
    Gearchiveerd: '',
    Conceptnummer: '',
    'Geografische toepassingsgebieden': 'Vlaams Gewest (BE2)',
    'Laatst ontvangen': '',
    Contactgegevens: '',
    filter: 'tools',
    filterTheme: 'burger',
  },
  {
    favorite: 'true',
    name: 'Beheer van mandatarissen',
    description:
      "Hou de mandatarissen binnen de gemeenten, OCMW's, disctricten en provincies bij",
    'Startdatum dienstverlening': '',
    'Einddatum dienstverlening': 'nvt',
    categorie: 'Burger en Overheid',
    'Thema(’s)': 'Lokaal bestuur',
    'Meer thema’s': 'geen match',
    'Laatst gewijzigd': '',
    'Aangemaakt op': '',
    Procedure: '',
    Bewijsstukken: '',
    Kosten: '',
    'Financieel voordeel': '',
    Uitzonderingen: '',
    'Bevoegde bestuursniveau’s': 'Vlaamse overheid',
    'Bevoegde organisaties':
      'https://wegwijs.vlaanderen.be/#/organisations/OVO001836',
    'Uitvoerende bestuursniveau’s': 'Vlaamse overheid',
    'Uitvoerende organisaties': '',
    link: 'https://loket.lokaalbestuur.vlaanderen.be/mandatenbeheer/mandatarissen',
    Regelgeving: '',
    'Links naar Vlaamse codex': '',
    Productnummer: '',
    Tags: '',
    Zoektermen: '',
    Publicatiekanalen: '',
    'Your Europe categorieën': '',
    Publicatielink: '',
    'Verwante producten': '',
    Deminimis: '',
    'Gestructureerde voorwaarden': '',
    Subsidiemaatregel: '',
    'u/je versie': '',
    Gearchiveerd: '',
    Conceptnummer: '',
    'Geografische toepassingsgebieden': 'Vlaams Gewest (BE2)',
    'Laatst ontvangen': '',
    Contactgegevens: '',
    filter: 'tools',
    filterTheme: 'burger',
  },
  {
    name: 'Beheer van leidinggevenden',
    description: 'Hou hier de leidinggevende functies voor uw bestuur bij',
    'Startdatum dienstverlening': '',
    'Einddatum dienstverlening': 'nvt',
    categorie: 'Burger en Overheid',
    'Thema(’s)': 'Lokaal bestuur',
    'Meer thema’s': 'geen match',
    'Laatst gewijzigd': '',
    'Aangemaakt op': '',
    Procedure: '',
    Bewijsstukken: '',
    Kosten: '',
    'Financieel voordeel': '',
    Uitzonderingen: '',
    'Bevoegde bestuursniveau’s': 'Vlaamse overheid',
    'Bevoegde organisaties':
      'https://wegwijs.vlaanderen.be/#/organisations/OVO001837',
    'Uitvoerende bestuursniveau’s': 'Vlaamse overheid',
    'Uitvoerende organisaties': '',
    link: 'https://loket.lokaalbestuur.vlaanderen.be/leidinggevendenbeheer/bestuursfuncties',
    Regelgeving: '',
    'Links naar Vlaamse codex': '',
    Productnummer: '',
    Tags: '',
    Zoektermen: '',
    Publicatiekanalen: '',
    'Your Europe categorieën': '',
    Publicatielink: '',
    'Verwante producten': '',
    Deminimis: '',
    'Gestructureerde voorwaarden': '',
    Subsidiemaatregel: '',
    'u/je versie': '',
    Gearchiveerd: '',
    Conceptnummer: '',
    'Geografische toepassingsgebieden': 'Vlaams Gewest (BE2)',
    'Laatst ontvangen': '',
    Contactgegevens: '',
    filter: 'tools',
    filterTheme: 'burger',
  },
  {
    favorite: 'true',
    name: 'Beheer van personeelsaantallen',
    description:
      'Hou hier de personeelsaantallen voor uw bestuur bij (aantal werknemers en voltijds equivalenten)',
    'Startdatum dienstverlening': '',
    'Einddatum dienstverlening': 'nvt',
    categorie: 'Burger en Overheid',
    'Thema(’s)': 'Lokaal bestuur',
    'Meer thema’s': 'geen match',
    'Laatst gewijzigd': '',
    'Aangemaakt op': '',
    Procedure: '',
    Bewijsstukken: '',
    Kosten: '',
    'Financieel voordeel': '',
    Uitzonderingen: '',
    'Bevoegde bestuursniveau’s': 'Vlaamse overheid',
    'Bevoegde organisaties':
      'https://wegwijs.vlaanderen.be/#/organisations/OVO001838',
    'Uitvoerende bestuursniveau’s': 'Vlaamse overheid',
    'Uitvoerende organisaties': '',
    link: 'https://loket.lokaalbestuur.vlaanderen.be/personeelsbeheer/personeelsaantallen',
    Regelgeving: '',
    'Links naar Vlaamse codex': '',
    Productnummer: '',
    Tags: '',
    Zoektermen: '',
    Publicatiekanalen: '',
    'Your Europe categorieën': '',
    Publicatielink: '',
    'Verwante producten': '',
    Deminimis: '',
    'Gestructureerde voorwaarden': '',
    Subsidiemaatregel: '',
    'u/je versie': '',
    Gearchiveerd: '',
    Conceptnummer: '',
    'Geografische toepassingsgebieden': 'Vlaams Gewest (BE2)',
    'Laatst ontvangen': '',
    Contactgegevens: '',
    filter: 'tools',
    filterTheme: 'burger',
  },
  {
    favorite: 'true',
    name: 'BBC-DR',
    description:
      'Bezorg de digitale rapporten aan de Vlaamse Regering over de beleids- en beheerscyclus',
    'Startdatum dienstverlening': '',
    'Einddatum dienstverlening': 'nvt',
    categorie: 'Burger en Overheid',
    'Thema(’s)': 'Lokaal bestuur',
    'Meer thema’s': 'geen match',
    'Laatst gewijzigd': '',
    'Aangemaakt op': '',
    Procedure: '',
    Bewijsstukken: '',
    Kosten: '',
    'Financieel voordeel': '',
    Uitzonderingen: '',
    'Bevoegde bestuursniveau’s': 'Vlaamse overheid',
    'Bevoegde organisaties':
      'https://wegwijs.vlaanderen.be/#/organisations/OVO001839',
    'Uitvoerende bestuursniveau’s': 'Vlaamse overheid',
    'Uitvoerende organisaties': '',
    link: 'https://loket.lokaalbestuur.vlaanderen.be/bbcdr/rapporten',
    Regelgeving: '',
    'Links naar Vlaamse codex': '',
    Productnummer: '',
    Tags: '',
    Zoektermen: '',
    Publicatiekanalen: '',
    'Your Europe categorieën': '',
    Publicatielink: '',
    'Verwante producten': '',
    Deminimis: '',
    'Gestructureerde voorwaarden': '',
    Subsidiemaatregel: '',
    'u/je versie': '',
    Gearchiveerd: '',
    Conceptnummer: '',
    'Geografische toepassingsgebieden': 'Vlaams Gewest (BE2)',
    'Laatst ontvangen': '',
    Contactgegevens: '',
    filter: 'tools',
    filterTheme: 'burger',
  },
  {
    name: 'Bestuurlijk Toezicht',
    description:
      'Bezorg besluiten en overzichtslijsten aan de toezichthoudende overheid',
    'Startdatum dienstverlening': '',
    'Einddatum dienstverlening': 'nvt',
    categorie: 'Burger en Overheid',
    'Thema(’s)': 'Lokaal bestuur',
    'Meer thema’s': 'geen match',
    'Laatst gewijzigd': '',
    'Aangemaakt op': '',
    Procedure: '',
    Bewijsstukken: '',
    Kosten: '',
    'Financieel voordeel': '',
    Uitzonderingen: '',
    'Bevoegde bestuursniveau’s': 'Vlaamse overheid',
    'Bevoegde organisaties':
      'https://wegwijs.vlaanderen.be/#/organisations/OVO001840',
    'Uitvoerende bestuursniveau’s': 'Vlaamse overheid',
    'Uitvoerende organisaties': '',
    link: 'https://loket.lokaalbestuur.vlaanderen.be/supervision/submissions',
    Regelgeving: '',
    'Links naar Vlaamse codex': '',
    Productnummer: '',
    Tags: '',
    Zoektermen: '',
    Publicatiekanalen: '',
    'Your Europe categorieën': '',
    Publicatielink: '',
    'Verwante producten': '',
    Deminimis: '',
    'Gestructureerde voorwaarden': '',
    Subsidiemaatregel: '',
    'u/je versie': '',
    Gearchiveerd: '',
    Conceptnummer: '',
    'Geografische toepassingsgebieden': 'Vlaams Gewest (BE2)',
    'Laatst ontvangen': '',
    Contactgegevens: '',
    filter: 'tools',
    filterTheme: 'burger',
  },
  {
    name: 'Berichtencentrum',
    description:
      'Bekijk en reageer op de berichten van de toezichthoudende overheid',
    'Startdatum dienstverlening': '',
    'Einddatum dienstverlening': 'nvt',
    categorie: 'Burger en Overheid',
    'Thema(’s)': 'Lokaal bestuur',
    'Meer thema’s': 'geen match',
    'Laatst gewijzigd': '',
    'Aangemaakt op': '',
    Procedure: '',
    Bewijsstukken: '',
    Kosten: '',
    'Financieel voordeel': '',
    Uitzonderingen: '',
    'Bevoegde bestuursniveau’s': 'Vlaamse overheid',
    'Bevoegde organisaties':
      'https://wegwijs.vlaanderen.be/#/organisations/OVO001841',
    'Uitvoerende bestuursniveau’s': 'Vlaamse overheid',
    'Uitvoerende organisaties': '',
    link: 'https://loket.lokaalbestuur.vlaanderen.be/berichtencentrum/berichten',
    Regelgeving: '',
    'Links naar Vlaamse codex': '',
    Productnummer: '',
    Tags: '',
    Zoektermen: '',
    Publicatiekanalen: '',
    'Your Europe categorieën': '',
    Publicatielink: '',
    'Verwante producten': '',
    Deminimis: '',
    'Gestructureerde voorwaarden': '',
    Subsidiemaatregel: '',
    'u/je versie': '',
    Gearchiveerd: '',
    Conceptnummer: '',
    'Geografische toepassingsgebieden': 'Vlaams Gewest (BE2)',
    'Laatst ontvangen': '',
    Contactgegevens: '',
    filter: 'tools',
    filterTheme: 'burger',
  },
  {
    name: 'Subsidiebeheer',
    description: 'Teken in op bepaalde openstaande subsidies',
    'Startdatum dienstverlening': '',
    'Einddatum dienstverlening': 'nvt',
    categorie: 'Burger en Overheid',
    'Thema(’s)': 'Lokaal bestuur',
    'Meer thema’s': 'Financieel voordeel',
    'Laatst gewijzigd': '',
    'Aangemaakt op': '',
    Procedure: '',
    Bewijsstukken: '',
    Kosten: '',
    'Financieel voordeel': '',
    Uitzonderingen: '',
    'Bevoegde bestuursniveau’s': 'Vlaamse overheid',
    'Bevoegde organisaties':
      'https://wegwijs.vlaanderen.be/#/organisations/OVO001842',
    'Uitvoerende bestuursniveau’s': 'Vlaamse overheid',
    'Uitvoerende organisaties': '',
    link: 'https://loket.lokaalbestuur.vlaanderen.be/subsidy/applications',
    Regelgeving: '',
    'Links naar Vlaamse codex': '',
    Productnummer: '',
    Tags: '',
    Zoektermen: '',
    Publicatiekanalen: '',
    'Your Europe categorieën': '',
    Publicatielink: '',
    'Verwante producten': '',
    Deminimis: '',
    'Gestructureerde voorwaarden': '',
    Subsidiemaatregel: '',
    'u/je versie': '',
    Gearchiveerd: '',
    Conceptnummer: '',
    'Geografische toepassingsgebieden': 'Vlaams Gewest (BE2)',
    'Laatst ontvangen': '',
    Contactgegevens: '',
    filter: 'tools',
    filterTheme: 'burger',
  },
  {
    name: 'Databank Erediensten',
    description:
      'Consulteer hier inzendingen van (centrale) besturen van de eredienst, gemeente- en provincieoverheid en representatief orgaan.',
    'Startdatum dienstverlening': '',
    'Einddatum dienstverlening': 'nvt',
    categorie: 'Burger en Overheid',
    'Thema(’s)': 'Lokaal bestuur',
    'Meer thema’s': 'geen match',
    'Laatst gewijzigd': '',
    'Aangemaakt op': '',
    Procedure: '',
    Bewijsstukken: '',
    Kosten: '',
    'Financieel voordeel': '',
    Uitzonderingen: '',
    'Bevoegde bestuursniveau’s': 'Vlaamse overheid',
    'Bevoegde organisaties':
      'https://wegwijs.vlaanderen.be/#/organisations/OVO001843',
    'Uitvoerende bestuursniveau’s': 'Vlaamse overheid',
    'Uitvoerende organisaties': '',
    link: 'https://databankerediensten.lokaalbestuur.vlaanderen.be',
    Regelgeving: '',
    'Links naar Vlaamse codex': '',
    Productnummer: '',
    Tags: '',
    Zoektermen: '',
    Publicatiekanalen: '',
    'Your Europe categorieën': '',
    Publicatielink: '',
    'Verwante producten': '',
    Deminimis: '',
    'Gestructureerde voorwaarden': '',
    Subsidiemaatregel: '',
    'u/je versie': '',
    Gearchiveerd: '',
    Conceptnummer: '',
    'Geografische toepassingsgebieden': 'Vlaams Gewest (BE2)',
    'Laatst ontvangen': '',
    Contactgegevens: '',
    filter: 'tools',
    filterTheme: 'burger',
  },
  {
    name: 'Organisaties Erediensten',
    description:
      'Consulteer hier de mandaten en bedienaren van de besturen van de eredienst',
    'Startdatum dienstverlening': '',
    'Einddatum dienstverlening': 'nvt',
    categorie: 'Burger en Overheid',
    'Thema(’s)': 'Lokaal bestuur',
    'Meer thema’s': 'geen match',
    'Laatst gewijzigd': '',
    'Aangemaakt op': '',
    Procedure: '',
    Bewijsstukken: '',
    Kosten: '',
    'Financieel voordeel': '',
    Uitzonderingen: '',
    'Bevoegde bestuursniveau’s': 'Vlaamse overheid',
    'Bevoegde organisaties':
      'https://wegwijs.vlaanderen.be/#/organisations/OVO001844',
    'Uitvoerende bestuursniveau’s': 'Vlaamse overheid',
    'Uitvoerende organisaties': '',
    link: 'https://organisaties.lokaalbestuur.vlaanderen.be',
    Regelgeving: '',
    'Links naar Vlaamse codex': '',
    Productnummer: '',
    Tags: '',
    Zoektermen: '',
    Publicatiekanalen: '',
    'Your Europe categorieën': '',
    Publicatielink: '',
    'Verwante producten': '',
    Deminimis: '',
    'Gestructureerde voorwaarden': '',
    Subsidiemaatregel: '',
    'u/je versie': '',
    Gearchiveerd: '',
    Conceptnummer: '',
    'Geografische toepassingsgebieden': 'Vlaams Gewest (BE2)',
    'Laatst ontvangen': '',
    Contactgegevens: '',
    filter: 'tools',
    filterTheme: 'burger',
  },
  {
    name: 'Verenigingen',
    description:
      'Consulteer uw verenigingen, zoals gekend inhet verenigingsregister en beheer de erkenningen van deze verenigingen',
    'Startdatum dienstverlening': '',
    'Einddatum dienstverlening': 'nvt',
    categorie: 'Burger en Overheid',
    'Thema(’s)': 'Lokaal bestuur',
    'Meer thema’s': 'geen match',
    'Laatst gewijzigd': '',
    'Aangemaakt op': '',
    Procedure: '',
    Bewijsstukken: '',
    Kosten: '',
    'Financieel voordeel': '',
    Uitzonderingen: '',
    'Bevoegde bestuursniveau’s': 'Vlaamse overheid',
    'Bevoegde organisaties':
      'https://wegwijs.vlaanderen.be/#/organisations/OVO001845',
    'Uitvoerende bestuursniveau’s': 'Vlaamse overheid',
    'Uitvoerende organisaties': '',
    link: 'https://verenigingen.lokaalbestuur.vlaanderen.be',
    Regelgeving: '',
    'Links naar Vlaamse codex': '',
    Productnummer: '',
    Tags: '',
    Zoektermen: '',
    Publicatiekanalen: '',
    'Your Europe categorieën': '',
    Publicatielink: '',
    'Verwante producten': '',
    Deminimis: '',
    'Gestructureerde voorwaarden': '',
    Subsidiemaatregel: '',
    'u/je versie': '',
    Gearchiveerd: '',
    Conceptnummer: '',
    'Geografische toepassingsgebieden': 'Vlaams Gewest (BE2)',
    'Laatst ontvangen': '',
    Contactgegevens: '',
    filter: 'tools',
    filterTheme: 'burger',
  },
  {
    name: 'Contact- en Organisatiegegevens',
    description:
      'Beheer uw contactgegevens en consulteer uw organisatiegegevens, zoals gekend bij Agentschap Binnenlands Bestuur.',
    'Startdatum dienstverlening': '',
    'Einddatum dienstverlening': 'nvt',
    categorie: 'Burger en Overheid',
    'Thema(’s)': 'Lokaal bestuur',
    'Meer thema’s': 'geen match',
    'Laatst gewijzigd': '',
    'Aangemaakt op': '',
    Procedure: '',
    Bewijsstukken: '',
    Kosten: '',
    'Financieel voordeel': '',
    Uitzonderingen: '',
    'Bevoegde bestuursniveau’s': 'Vlaamse overheid',
    'Bevoegde organisaties':
      'https://wegwijs.vlaanderen.be/#/organisations/OVO001846',
    'Uitvoerende bestuursniveau’s': 'Vlaamse overheid',
    'Uitvoerende organisaties': '',
    link: 'https://contactgegevens.lokaalbestuur.vlaanderen.be',
    Regelgeving: '',
    'Links naar Vlaamse codex': '',
    Productnummer: '',
    Tags: '',
    Zoektermen: '',
    Publicatiekanalen: '',
    'Your Europe categorieën': '',
    Publicatielink: '',
    'Verwante producten': '',
    Deminimis: '',
    'Gestructureerde voorwaarden': '',
    Subsidiemaatregel: '',
    'u/je versie': '',
    Gearchiveerd: '',
    Conceptnummer: '',
    'Geografische toepassingsgebieden': 'Vlaams Gewest (BE2)',
    'Laatst ontvangen': '',
    Contactgegevens: '',
    filter: 'tools',
    filterTheme: 'burger',
  },
  {
    name: 'Publieke leidinggevendendatabank',
    description:
      'Raadpleeg en hergebruik de gegevens van lokale leidinggevenden in deze publiek toegankelijke leidinggevendendatabank',
    'Startdatum dienstverlening': '',
    'Einddatum dienstverlening': 'nvt',
    categorie: 'Burger en Overheid',
    'Thema(’s)': 'Lokaal bestuur',
    'Meer thema’s': 'geen match',
    'Laatst gewijzigd': '',
    'Aangemaakt op': '',
    Procedure: '',
    Bewijsstukken: '',
    Kosten: '',
    'Financieel voordeel': '',
    Uitzonderingen: '',
    'Bevoegde bestuursniveau’s': 'Vlaamse overheid',
    'Bevoegde organisaties':
      'https://wegwijs.vlaanderen.be/#/organisations/OVO001847',
    'Uitvoerende bestuursniveau’s': 'Vlaamse overheid',
    'Uitvoerende organisaties': '',
    link: 'https://leidinggevenden.lokaalbestuur.vlaanderen.be/',
    Regelgeving: '',
    'Links naar Vlaamse codex': '',
    Productnummer: '',
    Tags: '',
    Zoektermen: '',
    Publicatiekanalen: '',
    'Your Europe categorieën': '',
    Publicatielink: '',
    'Verwante producten': '',
    Deminimis: '',
    'Gestructureerde voorwaarden': '',
    Subsidiemaatregel: '',
    'u/je versie': '',
    Gearchiveerd: '',
    Conceptnummer: '',
    'Geografische toepassingsgebieden': '',
    'Laatst ontvangen': '',
    Contactgegevens: '',
    filter: 'tools',
    filterTheme: 'burger',
  },
  {
    name: 'Publieke Besluitendatabank',
    description:
      'Verzamelplaats voor meldingsplichtige besluiten. Beschikbaar voor lokale en centrale overheden',
    'Startdatum dienstverlening': '',
    'Einddatum dienstverlening': 'nvt',
    categorie: 'Burger en Overheid',
    'Thema(’s)': 'Lokaal bestuur',
    'Meer thema’s': 'geen match',
    'Laatst gewijzigd': '',
    'Aangemaakt op': '',
    Procedure: '',
    Bewijsstukken: '',
    Kosten: '',
    'Financieel voordeel': '',
    Uitzonderingen: '',
    'Bevoegde bestuursniveau’s': 'Vlaamse overheid',
    'Bevoegde organisaties':
      'https://wegwijs.vlaanderen.be/#/organisations/OVO001848',
    'Uitvoerende bestuursniveau’s': 'Vlaamse overheid',
    'Uitvoerende organisaties': '',
    link: 'https://besluiten.lokaalbestuur.vlaanderen.be',
    Regelgeving: '',
    'Links naar Vlaamse codex': '',
    Productnummer: '',
    Tags: '',
    Zoektermen: '',
    Publicatiekanalen: '',
    'Your Europe categorieën': '',
    Publicatielink: '',
    'Verwante producten': '',
    Deminimis: '',
    'Gestructureerde voorwaarden': '',
    Subsidiemaatregel: '',
    'u/je versie': '',
    Gearchiveerd: '',
    Conceptnummer: '',
    'Geografische toepassingsgebieden': '',
    'Laatst ontvangen': '',
    Contactgegevens: '',
    filter: 'tools',
    filterTheme: 'burger',
  },
  {
    name: 'Lokaal Beslist',
    description:
      'Ben je benieuwd naar de aanpak van andere gemeenten rond bepaalde thema’s? Heb je inspiratie nodig voor lokale besluitvorming? Ontdek met Lokaal Beslist wat er speelt in andere Vlaamse gemeenten en hoe zij omgaan met vergelijkbare uitdagingen',
    'Startdatum dienstverlening': '',
    'Einddatum dienstverlening': 'nvt',
    categorie: 'Burger en Overheid',
    'Thema(’s)': 'Lokaal bestuur',
    'Meer thema’s': 'geen match',
    'Laatst gewijzigd': '',
    'Aangemaakt op': '',
    Procedure: '',
    Bewijsstukken: '',
    Kosten: '',
    'Financieel voordeel': '',
    Uitzonderingen: '',
    'Bevoegde bestuursniveau’s': 'Vlaamse overheid',
    'Bevoegde organisaties':
      'https://wegwijs.vlaanderen.be/#/organisations/OVO001849',
    'Uitvoerende bestuursniveau’s': 'Vlaamse overheid',
    'Uitvoerende organisaties': '',
    link: 'https://lokaalbeslist.vlaanderen.be/',
    Regelgeving: '',
    'Links naar Vlaamse codex': '',
    Productnummer: '',
    Tags: '',
    Zoektermen: '',
    Publicatiekanalen: '',
    'Your Europe categorieën': '',
    Publicatielink: '',
    'Verwante producten': '',
    Deminimis: '',
    'Gestructureerde voorwaarden': '',
    Subsidiemaatregel: '',
    'u/je versie': '',
    Gearchiveerd: '',
    Conceptnummer: '',
    'Geografische toepassingsgebieden': '',
    'Laatst ontvangen': '',
    Contactgegevens: '',
  },
];